on: [push, pull_request]
name: ci

permissions:
    contents: read

env:
    LOCAL_USERNAME: DailyDriver
    LOCAL_USERPASS: 4FW9kwTsGMGf4VvjZ33mfsET
    INSTALL_PACKAGES: 0

jobs:
    setup-scoop:
        name: Setup Environment
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Create User Account for Transferring Ownership
              run: |
                $options = @{
                    Name = "${{env.LOCAL_USERNAME}}"
                    Password = ConvertTo-SecureString -String "${{env.LOCAL_USERPASS}}" -AsPlainText -Force
                }
                New-LocalUser @options
                Add-LocalGroupMember -Group "Administrators" -Member "${{env.LOCAL_USERNAME}}"
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Environment
              run: |
                $pass = ConvertTo-SecureString -String "${{env.LOCAL_USERPASS}}" -AsPlainText -Force
                $cred = [System.Management.Automation.PSCredential]::new("${{env.LOCAL_USERNAME}}", $pass)
                Invoke-Command -ComputerName $env:COMPUTERNAME -Credential $cred -FilePath ".\setup_env.ps1" -ArgumentList $pwd.Path
            - name: Upload Environment Archive
              if: ${{env.INSTALL_PACKAGES == 1}}
              uses: actions/upload-artifact@v4
              with:
                name: env
                path: env
                compression-level: 9