on: [push, pull_request]
name: ci

permissions:
    contents: read

env:
    LOCAL_USERNAME: DailyDriver
    LOCAL_USERPASS: 123
    INSTALL_PACKAGES: 0

jobs:
    setup-scoop:
        name: Setup Environment
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Create User Account for Transferring Ownership
              run: |
                try {
                    $options = @{
                        Name = "${{env.LOCAL_USERNAME}}"
                        Password = ConvertTo-SecureString -String "${{env.LOCAL_USERPASS}}" -AsPlainText -Force
                    }
                    New-LocalUser @options
                    Add-LocalGroupMember -Group "Administrators" -Member "${{env.LOCAL_USERNAME}}"
                } catch {
                    Write-Host $_
                    throw
                }
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Environment
              run: |
                $cred = @{
                    UserName = "${{env.LOCAL_USERNAME}}"
                    Password = ConvertTo-SecureString -String "${{env.LOCAL_USERPASS}}" -AsPlainText -Force
                }
                Start-Process -FilePath "pwsh.exe" -ArgumentList "-NoProfile","-NoLogo","-Command",". .\setup_env.ps1" -NoWait -Credential $cred
            - name: Upload Environment Archive
              uses: actions/upload-artifact@v4
              with:
                name: env
                path: env
                compression-level: 9